version: "3.8"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"  # LocalStack Gateway
    environment:
      - SERVICES=lambda
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
    volumes:
      - "./localstack:/var/lib/localstack"  # Optional volume for persistence
      - "/var/run/docker.sock:/var/run/docker.sock"  # Mount Docker socket for Lambda execution
