version: "3.8"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566" # LocalStack Gateway
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
    volumes:
      - "./localstack:/var/lib/localstack" # Optional for persistence
